base_url: 'https://craftcms.com/docs'
preserve_hierarchy: true
files:
  - source: /docs/1.x/**/*.md
    ignore:
      - /docs/1.x/ja
      - /docs/1.x/fr
    translation: /docs/1.x/%two_letters_code%/**/%original_file_name%
